name: Chisel Proxy Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Copy Chisel .deb Package
        run: |
          cp chisel_1.11.5_linux_amd64.deb chisel.deb
          sudo dpkg -i chisel.deb

      - name: Start Chisel Server
        run: |
          chisel server --reverse --port 8080 &

      - name: Run Chisel Client
        run: |
          chisel client --proxy http://localhost:8080 10.0.0.1:9090 R:http
